# -*- coding: utf-8 -*-
"""textSummarizeandGenerate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7coBj3zUF5-vkGtizO9q4l2P73wJLf3
"""

!pip install gradio
!pip install transformers
!pip install tensorflow

!pip install tf-keras --upgrade

import gradio as gr
from transformers import pipeline, TFGPT2LMHeadModel, GPT2Tokenizer
import tensorflow as tf

tokenizer = GPT2Tokenizer.from_pretrained("gpt2-xl")
model = TFGPT2LMHeadModel.from_pretrained("gpt2-xl", pad_token_id=tokenizer.eos_token_id)

def generate_text(input):
  input_ids = tokenizer.encode(input, return_tensors='tf')
  beam_output = model.generate(input_ids, max_length=2000, num_beams=10, no_repeat_ngram_size=2, early_stopping=True)
  output = tokenizer.decode(beam_output[0], skip_special_tokens=True, clean_up_tokenization_spaces=True)
  return '.'.join(output.split('.')[:-1]) + '.'

text="Artificial Intelligence is revolutionizing the world of healthcare by enabling faster diagnoses, personalized treatments,"
generate_text(text)

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def summarize_text(text):
  summary = summarizer(text, max_length=100, min_length=30, do_sample=False)[0]['summary_text']
  return summary

text="In recent years, the rapid advancement of artificial intelligence has significantly transformed various industries, including healthcare, finance, education, and transportation. AI-powered tools are now capable of analyzing vast amounts of data, recognizing patterns, and making predictions with remarkable accuracy. In the healthcare sector, for instance, AI algorithms assist doctors in diagnosing diseases more quickly and accurately than ever before, improving patient outcomes. In finance, automated trading systems and fraud detection mechanisms have become essential components of modern banking. Educational platforms leverage AI to personalize learning experiences for students, adapting content to suit individual needs and learning speeds. Meanwhile, autonomous vehicles and smart traffic systems are reshaping transportation, making travel safer and more efficient. However, these advancements also raise ethical concerns, such as data privacy, algorithmic bias, and job displacement, which must be carefully addressed as AI continues to evolve and integrate into daily life."
summarize_text(text)

# Define a combined function to handle both tasks
def combined_function(text_to_generate, text_to_summarize):
  generated_text = generate_text(text_to_generate)
  summarized_text = summarize_text(text_to_summarize)
  return generated_text, summarized_text

# Create interface using gradio
summary_input = gr.Textbox(lines=5, placeholder="Enter text to summarize here...")
summary_output = gr.Textbox()
output_text = gr.Textbox()

iface = gr.Interface(
    fn=combined_function, # Pass the combined function here
    inputs=[
        gr.Textbox(lines=2, placeholder="Enter your text here..."),
        summary_input
    ],
    outputs=[output_text, summary_output],
    title="Text Generation and Summarization",
    description="Generate text and summarize text using AI. \n Harness the power of AI to generate human-like text from any prompt. Whether you're crafting stories, summarizing content, or building dialogues, this tool uses advanced language models to deliver coherent and creative results.")

iface.launch(debug=True)